(package "jetbrains"
         "0.0.1"
         "JetBrains IDE bridge")

(website-url "https://github.com/emacs-php/jetbrains.el")
(keywords "tools" "php")

(package-file "jetbrains.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "24.3")
(depends-on "cl-lib" "0.5")
(depends-on "f" "0.17")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
